/**
 * Form schemas for tabular tasks.
 *
 * Each schema describes the fields the user edits. The backend has its own
 * canonical feature order — we send whatever keys are in the schema and the
 * backend falls back to baseline values for anything missing.
 */

export const TABULAR_SCHEMAS = {
  'titanic-survival': {
    endpoint: '/tabular/predict-titanic',
    submitLabel: 'Predict survival',
    gaugeLabel: 'Survival probability',
    positiveClass: 'Survived',
    fields: [
      {
        key: 'pclass',
        label: 'Passenger class',
        help: '1 = first, 3 = steerage',
        type: 'select',
        options: [
          { value: 1, label: '1st class' },
          { value: 2, label: '2nd class' },
          { value: 3, label: '3rd class' },
        ],
      },
      {
        key: 'sex',
        label: 'Sex',
        type: 'select',
        options: [
          { value: 'female', label: 'Female' },
          { value: 'male', label: 'Male' },
        ],
      },
      { key: 'age', label: 'Age', type: 'slider', min: 0, max: 80, step: 1, unit: 'yrs' },
      {
        key: 'sibsp',
        label: 'Siblings / spouses aboard',
        type: 'slider',
        min: 0,
        max: 8,
        step: 1,
      },
      {
        key: 'parch',
        label: 'Parents / children aboard',
        type: 'slider',
        min: 0,
        max: 6,
        step: 1,
      },
      { key: 'fare', label: 'Fare paid', type: 'slider', min: 0, max: 300, step: 1, unit: '£' },
      {
        key: 'embarked',
        label: 'Port of embarkation',
        type: 'select',
        options: [
          { value: 'C', label: 'Cherbourg (C)' },
          { value: 'Q', label: 'Queenstown (Q)' },
          { value: 'S', label: 'Southampton (S)' },
        ],
      },
    ],
    presets: [
      {
        label: 'Female · 1st class · age 22',
        values: {
          pclass: 1,
          sex: 'female',
          age: 22,
          sibsp: 0,
          parch: 0,
          fare: 75,
          embarked: 'C',
        },
      },
      {
        label: 'Male · 3rd class · age 30',
        values: {
          pclass: 3,
          sex: 'male',
          age: 30,
          sibsp: 0,
          parch: 0,
          fare: 8,
          embarked: 'S',
        },
      },
      {
        label: 'Family w/ 2 kids · 2nd class',
        values: {
          pclass: 2,
          sex: 'female',
          age: 36,
          sibsp: 1,
          parch: 2,
          fare: 35,
          embarked: 'S',
        },
      },
    ],
    defaults: {
      pclass: 3,
      sex: 'male',
      age: 28,
      sibsp: 0,
      parch: 0,
      fare: 14,
      embarked: 'S',
    },
  },

  'heart-disease': {
    endpoint: '/tabular/predict-heart',
    submitLabel: 'Estimate heart risk',
    gaugeLabel: 'Heart disease probability',
    positiveClass: 'Elevated risk',
    fields: [
      { key: 'age', label: 'Age', type: 'slider', min: 29, max: 77, step: 1, unit: 'yrs' },
      {
        key: 'sex',
        label: 'Sex',
        type: 'select',
        options: [
          { value: 0, label: 'Female' },
          { value: 1, label: 'Male' },
        ],
      },
      {
        key: 'cp',
        label: 'Chest pain type',
        help: '1 typical angina · 4 asymptomatic',
        type: 'select',
        options: [
          { value: 1, label: 'Typical angina (1)' },
          { value: 2, label: 'Atypical angina (2)' },
          { value: 3, label: 'Non-anginal pain (3)' },
          { value: 4, label: 'Asymptomatic (4)' },
        ],
      },
      {
        key: 'trestbps',
        label: 'Resting blood pressure',
        type: 'slider',
        min: 90,
        max: 200,
        step: 1,
        unit: 'mmHg',
      },
      {
        key: 'chol',
        label: 'Serum cholesterol',
        type: 'slider',
        min: 100,
        max: 600,
        step: 1,
        unit: 'mg/dL',
      },
      {
        key: 'fbs',
        label: 'Fasting blood sugar > 120 mg/dL',
        type: 'select',
        options: [
          { value: 0, label: 'No' },
          { value: 1, label: 'Yes' },
        ],
      },
      {
        key: 'restecg',
        label: 'Resting ECG',
        type: 'select',
        options: [
          { value: 0, label: 'Normal (0)' },
          { value: 1, label: 'ST-T abnormality (1)' },
          { value: 2, label: 'LV hypertrophy (2)' },
        ],
      },
      {
        key: 'thalach',
        label: 'Max heart rate',
        type: 'slider',
        min: 70,
        max: 210,
        step: 1,
        unit: 'bpm',
      },
      {
        key: 'exang',
        label: 'Exercise-induced angina',
        type: 'select',
        options: [
          { value: 0, label: 'No' },
          { value: 1, label: 'Yes' },
        ],
      },
      {
        key: 'oldpeak',
        label: 'ST depression (oldpeak)',
        type: 'slider',
        min: 0,
        max: 6,
        step: 0.1,
      },
    ],
    presets: [
      {
        label: 'Healthy baseline',
        values: {
          age: 45,
          sex: 0,
          cp: 3,
          trestbps: 120,
          chol: 200,
          fbs: 0,
          restecg: 0,
          thalach: 170,
          exang: 0,
          oldpeak: 0.2,
        },
      },
      {
        label: 'Moderate risk',
        values: {
          age: 58,
          sex: 1,
          cp: 3,
          trestbps: 140,
          chol: 260,
          fbs: 0,
          restecg: 1,
          thalach: 140,
          exang: 0,
          oldpeak: 1.5,
        },
      },
      {
        label: 'High-risk profile',
        values: {
          age: 65,
          sex: 1,
          cp: 4,
          trestbps: 150,
          chol: 300,
          fbs: 1,
          restecg: 2,
          thalach: 120,
          exang: 1,
          oldpeak: 3.5,
        },
      },
    ],
    defaults: {
      age: 54,
      sex: 1,
      cp: 3,
      trestbps: 130,
      chol: 246,
      fbs: 0,
      restecg: 1,
      thalach: 150,
      exang: 0,
      oldpeak: 1.0,
    },
  },

  'wine-quality': {
    endpoint: '/tabular/predict-wine',
    submitLabel: 'Rate wine quality',
    gaugeLabel: 'Quality distribution',
    positiveClass: 'High (≥7)',
    fields: [
      {
        key: 'alcohol',
        label: 'Alcohol',
        type: 'slider',
        min: 8,
        max: 15,
        step: 0.1,
        unit: '% vol',
      },
      {
        key: 'volatile_acidity',
        label: 'Volatile acidity',
        type: 'slider',
        min: 0.1,
        max: 1.6,
        step: 0.01,
        unit: 'g/L',
      },
      {
        key: 'sulphates',
        label: 'Sulphates',
        type: 'slider',
        min: 0.3,
        max: 2.0,
        step: 0.01,
        unit: 'g/L',
      },
      {
        key: 'citric_acid',
        label: 'Citric acid',
        type: 'slider',
        min: 0,
        max: 1.0,
        step: 0.01,
        unit: 'g/L',
      },
      {
        key: 'residual_sugar',
        label: 'Residual sugar',
        type: 'slider',
        min: 0.5,
        max: 15,
        step: 0.1,
        unit: 'g/L',
      },
      {
        key: 'chlorides',
        label: 'Chlorides',
        type: 'slider',
        min: 0.01,
        max: 0.6,
        step: 0.005,
        unit: 'g/L',
      },
      { key: 'pH', label: 'pH', type: 'slider', min: 2.8, max: 4.0, step: 0.01 },
      {
        key: 'density',
        label: 'Density',
        type: 'slider',
        min: 0.99,
        max: 1.005,
        step: 0.0005,
        unit: 'g/cm³',
      },
    ],
    presets: [
      {
        label: 'Premium profile',
        values: {
          alcohol: 12.5,
          volatile_acidity: 0.3,
          sulphates: 0.9,
          citric_acid: 0.5,
          residual_sugar: 2.0,
          chlorides: 0.05,
          pH: 3.3,
          density: 0.995,
        },
      },
      {
        label: 'Average red',
        values: {
          alcohol: 10.4,
          volatile_acidity: 0.53,
          sulphates: 0.66,
          citric_acid: 0.27,
          residual_sugar: 2.5,
          chlorides: 0.087,
          pH: 3.31,
          density: 0.9967,
        },
      },
      {
        label: 'Faulty batch',
        values: {
          alcohol: 9.0,
          volatile_acidity: 1.1,
          sulphates: 0.45,
          citric_acid: 0.05,
          residual_sugar: 3.0,
          chlorides: 0.15,
          pH: 3.4,
          density: 0.999,
        },
      },
    ],
    defaults: {
      alcohol: 10.4,
      volatile_acidity: 0.53,
      sulphates: 0.66,
      citric_acid: 0.27,
      residual_sugar: 2.5,
      chlorides: 0.087,
      pH: 3.31,
      density: 0.9967,
    },
  },
}

export function getSchema(problemId) {
  return TABULAR_SCHEMAS[problemId] || null
}
